baseURL = "https://schwab.cloud"
languageCode = "en-us"
title = "Benedikt Schwab"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 1

  [[menu.main]]
    name = "Photography"
    url = "/photography"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[params]
    since = 2020
    author = "Benedikt Schwab"                           # Author's name
    avatar = "images/avatar.jpg"           # Author's avatar
    subtitle = ""         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank"> 4.0</a>'

[params.social]
    GitHub = "b-schwab"
    LinkedIn = "benedikt-schwab"
    Email   = "benedikt@schwab.cloud"
